# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6s",
  "iPhone 6s Plus",
  "iPhone 5s",
  "iPhone 4s",
  "iPad 2",
  "iPad Pro"
])

languages([
  "en-US",
  "ru"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "Overlap"

number_of_retries 3

output_directory "./screenshots"

erase_simulator true

reinstall_app true

clear_previous_screenshots true

workspace "./Overlap.xcworkspace"
